-- 한 줄 주석
/* 범위 주석 */

-- SQL 한 줄 실행 : 컨트롤 엔터

/* SYS 관리자 계정으로 수행하는 SQL */

ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

CREATE USER KH_KSY IDENTIFIED BY KH1234;

GRANT RESOURCE, CONNECT TO KH_KSY;

ALTER USER KH_KSY DEFAULT TABLESPACE
USERS QUOTA 20M ON USERS;