CREATE TABLE BASEBALL_TEAM(
		TEAM_NAME VARCHAR(20) PRIMARY KEY
);


		
INSERT INTO BASEBALL_TEAM VALUES ('두산');
INSERT INTO BASEBALL_TEAM VALUES ('기아');
INSERT INTO BASEBALL_TEAM VALUES ('삼성');
INSERT INTO BASEBALL_TEAM VALUES ('LG');
INSERT INTO BASEBALL_TEAM VALUES ('KT');
INSERT INTO BASEBALL_TEAM VALUES ('한화');
INSERT INTO BASEBALL_TEAM VALUES ('롯데');
INSERT INTO BASEBALL_TEAM VALUES ('키움');
INSERT INTO BASEBALL_TEAM VALUES ('SSG');
INSERT INTO BASEBALL_TEAM VALUES ('NC');

SELECT * FROM BASEBALL_TEAM;

CREATE TABLE BASEBALL_PALYER(
		PLAYER_NAME VARCHAR(10) PRIMARY KEY,
		POSTION     VARCHAR(10),
		TEAM_NAME   VARCHAR(20) NOT NULL,
		
);
