/* 관리자 계정(sys) 접속 후 수행 */

ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;


-- 계정 생성
CREATE USER REPRT IDENTIFIED BY RP1234;

-- 권한 부여
GRANT CONNECT, RESOURCE TO REPET;

-- 테이블 저장 공간 할당
ALTER USER REPET
DEFAULT TABLESPACE USERS
QUOTA 100M ON USERS;