ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;


-- 계정 생성
CREATE USER PEPET_KSY IDENTIFIED BY REPET1234;

-- 권한 부여
GRANT CONNECT, RESOURCE TO REPET_KSY;

-- 테이블 저장 공간 할당
ALTER USER SPRING_KSY
DEFAULT TABLESPACE USERS
QUOTA 100M ON USERS;