-- 한 줄 주석
/* 범위 주석 */

-- SQL 한 줄 실행 : 컨트롤 엔터

/* SYS 관리자 계정으로 수행하는 SQL */

ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

CREATE USER KH_PLKLJ IDENTIFIED BY PLKLJ1234;

GRANT RESOURCE, CONNECT TO KH_PLKLJ;

ALTER USER KH_PLKLJ DEFAULT TABLESPACE
USERS QUOTA 20M ON USERS;

CREATE SEQUENCE SEQ_ARTIST_ID START WITH 1 INCREMENT BY 1;







SELECT * FROM ARTIST; 
SELECT * FROM "MEMBER"; 
SELECT * FROM PIECE; 
SELECT * FROM PIECE_CATEGORY; 
SELECT * FROM REPORT; 
SELECT * FROM VISITOR; 
SELECT * FROM "WORK"; 
SELECT * FROM FOLLOW; 
SELECT * FROM PIECE_SELL; 
SELECT * FROM PAYMENT_RECORD; 
SELECT * FROM ARTIST WHERE MEMBER_NO = 16;
SELECT * FROM WORK WHERE MEMBER_NO = 16;
SELECT * FROM PIECE WHERE MEMBER_NO = 16;

UPDATE PIECE
SET PIECE_STATUS = 'F'
WHERE PIECE_NO = 91;

MERGE INTO VISITOR V
	USING (
	    SELECT TRUNC(SYSDATE) AS VISITOR_DATE, '192.168.10.29' AS VISITOR_IP
	    FROM DUAL
	) D
	ON (V.VISITOR_DATE = D.VISITOR_DATE)
	WHEN MATCHED THEN
	    UPDATE SET V.DAILY_VISITS = V.DAILY_VISITS + 1
	WHEN NOT MATCHED THEN
    INSERT (VISITOR_DATE, DAILY_VISITS, WEEK_GROUP, VISITOR_IP)
    VALUES (D.VISITOR_DATE, 1, TO_CHAR(D.VISITOR_DATE, 'YYYYWW'), D.VISITOR_IP);


  	SELECT
			A.MEMBER_NO, A.ARTIST_PROFILE, A.ARTIST_NICKNAME,
			W.WORK_DETAIL, M.MEMBER_NAME
		FROM 
			ARTIST A
		LEFT JOIN 
			MEMBER M ON (A.MEMBER_NO = M.MEMBER_NO)
		LEFT JOIN 
			WORK W ON (A.MEMBER_NO = W.MEMBER_NO)
		WHERE
			A.MEMBER_NO = 24
		
		AND 
			M.MEMBER_DEL_FL = 'N';

UPDATE ARTIST SET ARTIST_REG = 'D' WHERE ARTIST.MEMBER_NO = 1;COMMIT;

UPDATE PIECE
SET PIECE_STATUS = 'N'
WHERE PIECE_NO = 17;

UPDATE PIECE
SET PIECE_TYPE = 1
WHERE PIECE_NO = 17;

COMMIT;


  SELECT 
        	PIECE_TITLE, SIZE_X, SIZE_Y,
        	PIECE_STATUS, SELL_PRICE
        FROM PIECE P
        JOIN PIECE_SELL S ON (P.PIECE_NO = S.PIECE_NO)
        WHERE PIECE_STATUS = 'N'
        AND   PIECE_TYPE = 1;
        

        SELECT COUNT(*) FROM PIECE
        WHERE PIECE_STATUS = 'N';
       



				SELECT 
        	P.PIECE_NO, PIECE_TITLE, SIZE_X, SIZE_Y,
        	PIECE_STATUS, SELL_PRICE, ARTIST_NICKNAME
        FROM PIECE P
        LEFT JOIN PIECE_SELL S ON (P.PIECE_NO = S.PIECE_NO)
        LEFT JOIN ARTIST A ON (P.MEMBER_NO = A.MEMBER_NO)
        WHERE PIECE_STATUS = 'N'
        AND   PIECE_TYPE = 1
        ORDER BY P.PIECE_NO DESC;
       
       
       SELECT * FROM PIECE
        WHERE PIECE_STATUS = 'N'
        AND   PIECE_TYPE = 1;


				SELECT 
        	P.PIECE_NO, PIECE_TITLE, SIZE_X, SIZE_Y,
        	PIECE_STATUS, SELL_PRICE, ARTIST_NICKNAME
        FROM PIECE P
        JOIN PIECE_SELL S ON (P.PIECE_NO = S.PIECE_NO)
        JOIN ARTIST A ON (P.MEMBER_NO = A.MEMBER_NO)
        WHERE PIECE_STATUS = 'F'
        AND   PIECE_TYPE = 1
        ORDER BY P.PIECE_NO DESC;
       

INSERT INTO REPORT
		VALUES(
			SEQ_REPORT_NO.NEXTVAL,
			2,
			14,
			1,
			'욕설',
			DEFAULT, DEFAULT, DEFAULT
		);
	
	
	SELECT
	*
	FROM
		REPORT r;


SELECT
			A.MEMBER_NO,
			A.ARTIST_PROFILE,
			M.MEMBER_NAME
		FROM 
			ARTIST A
		JOIN MEMBER M ON (A.MEMBER_NO = M.MEMBER_NO)
		WHERE 
			A.ARTIST_REG = 'Y'
		ORDER BY
			A.MEMBER_NO ASC;
		
SELECT
			P.PIECE_NO, P.PIECE_TITLE, 
			P.SIZE_X, P.SIZE_Y,
			P.PIECE_RENAME, PS.SELL_PRICE
		FROM
			PIECE P
		LEFT JOIN
			PIECE_SELL PS ON (P.PIECE_NO = PS.PIECE_NO)
		WHERE
			P.MEMBER_NO = 7;


INSERT INTO PIECE_SELL
VALUES(20, 50000);

SELECT 
        	P.PIECE_NO, PIECE_TITLE, SIZE_X, SIZE_Y,
        	PIECE_STATUS, SELL_PRICE, ARTIST_NICKNAME, P.PIECE_RENAME,
        	M.MEMBER_NAME
        	
        FROM PIECE P
        LEFT JOIN PIECE_SELL S ON (P.PIECE_NO = S.PIECE_NO)
        LEFT JOIN ARTIST A ON (P.MEMBER_NO = A.MEMBER_NO)
        JOIN      MEMBER M ON (A.MEMBER_NO = M.MEMBER_NO)
        WHERE A.MEMBER_NO = 2;
       
SELECT * FROM MEMBER WHERE MEMBER_NO = 2;
SELECT * FROM ARTIST WHERE MEMBER_NO = 2;

SELECT COUNT(*)
		FROM FOLLOW
		WHERE 
			MEMBER_NO = 2
		AND 
			ARTIST_NO = 2;
		
INSERT INTO FOLLOW
		VALUES(2, 2);

SELECT COUNT(*)
		FROM FOLLOW
		WHERE MEMBER_NO = 2;


SELECT
			A.MEMBER_NO, A.ARTIST_PROFILE, A.ARTIST_NICKNAME,
			W.WORK_DETAIL, M.MEMBER_NAME,
			
			(SELECT COUNT(*) FROM FOLLOW WHERE MEMBER_NO = A.MEMBER_NO) AS FOLLOW_COUNT,
			
			(SELECT COUNT(*)
				FROM FOLLOW
				WHERE MEMBER_NO = 2
				AND   ARTIST_NO = 2) AS FOLLOW_CHECK 
			
		FROM 
			ARTIST A
		LEFT JOIN 
			MEMBER M ON (A.MEMBER_NO = M.MEMBER_NO)
		LEFT JOIN 
			WORK W ON (A.MEMBER_NO = W.MEMBER_NO)
		WHERE
			A.MEMBER_NO = 2
		AND 
			M.MEMBER_DEL_FL = 'N';


SELECT COUNT(*) FROM FOLLOW WHERE MEMBER_NO = MEMBER_NO) AS FOLLOW_COUNT;


INSERT INTO PIECE 
VALUES(
	SEQ_PIECE_NO.NEXTVAL, 8,
	'https://firebasestorage.googleapis.com/v0/b/odagirijoe-3e3a4.firebasestorage.app/o/piece%2F%EC%83%98%ED%94%8C%20(17).jpg?alt=media&token=8812128d-d5e2-42fc-87cc-38612e349e07',
	'구매작품 테스트', '구매작품', 10, 10,
	DEFAULT, 1, 'N', '5'
);


SELECT
			P.PIECE_NO, P.PIECE_TITLE, 
			P.SIZE_X, P.SIZE_Y,
			P.PIECE_RENAME, PS.SELL_PRICE
		FROM
			PIECE P
		LEFT JOIN
			PIECE_SELL PS ON (P.PIECE_NO = PS.PIECE_NO)
		WHERE
			P.MEMBER_NO = 2
		AND 
			P.PIECE_STATUS IN ('N', 'F');
		
		SELECT
			P.PIECE_NO, P.PIECE_TITLE, 
			P.SIZE_X, P.SIZE_Y,
			P.PIECE_RENAME,
			P.PIECE_STATUS,
			PS.SELL_PRICE
		FROM
			PIECE P
		LEFT JOIN
			PIECE_SELL PS ON (P.PIECE_NO = PS.PIECE_NO)
		WHERE
			P.MEMBER_NO = 2
		AND 
			P.PIECE_STATUS IN ('N', 'F', 'A', 'S');
	
		

CREATE TABLE "VISITOR" (
	"VISITOR_DATE"	DATE		NOT NULL,
	"DAILY_VISITS"	NUMBER	DEFAULT 0	NOT NULL,
	"WEEK_GROUP"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "VISITOR"."VISITOR_DATE" IS '방문 날짜';

COMMENT ON COLUMN "VISITOR"."DAILY_VISITS" IS '해당날짜의 방문자 수';

COMMENT ON COLUMN "VISITOR"."WEEK_GROUP" IS '주차를 나타내는 그룹 번호';

ALTER TABLE "VISITOR" ADD CONSTRAINT "PK_VISITOR" PRIMARY KEY (
	"VISITOR_DATE"
);


ALTER TABLE VISITOR ADD VISITOR_IP VARCHAR2(50);

COMMENT ON COLUMN "VISITOR"."VISITOR_IP" IS '방문자 IP';


SELECT 
			TO_CHAR(PAY_DATE, 'YYYY-MM-DD') AS PAY_DATE,
			SUM(PAY_AMOUNT) AS DAILY_TOTAL
		FROM 
			PAYMENT_RECORD
		GROUP BY
			TO_CHAR(PAY_DATE, 'YYYY-MM-DD')
		ORDER BY
			PAY_DATE;
		
		SELECT
			SUM(PAY_AMOUNT)
		FROM 
			PAYMENT_RECORD
		WHERE
			PAY_DATE >= SYSDATE - 7;











SELECT 
			TO_CHAR(REG_DATE, 'YYYY-MM-DD') AS regDate,
			COUNT(*) AS pieceCount
		FROM
			PIECE
		WHERE
			REG_DATE >= TRUNC(SYSDATE) - 6
		AND
			PIECE_STATUS = 'F'
		GROUP BY
			TO_CHAR(REG_DATE, 'YYYY-MM-DD')
		ORDER BY
			TO_CHAR(REG_DATE, 'YYYY-MM-DD');

SELECT
			NVL(COUNT(*), 0)
		FROM
			PIECE
		WHERE
			TO_CHAR(REG_DATE, 'YYYY-MM') = TO_CHAR(SYSDATE, 'YYYY-MM')
		AND
			PIECE_STATUS = 'F';
		
SELECT
			COUNT(*)
		FROM
			PIECE
		WHERE
			TO_CHAR(REG_DATE, 'YYYY-MM') = TO_CHAR(SYSDATE, 'YYYY-MM')
		AND
			PIECE_STATUS = 'F';


INSERT INTO PIECE
VALUES(SEQ_PIECE_NO.NEXTVAL, 2, 'https://firebasestorage.googleapis.com/v0/b/odagirijoe-3e3a4.firebasestorage.app/o/piece%2F%EC%83%98%ED%94%8C%20(17).jpg?alt=media&token=8812128d-d5e2-42fc-87cc-38612e349e07',
			 '대쉬보드 테스트', '판매완료', 13, 13, DEFAULT, 1, 'F', 5);
INSERT INTO PIECE
VALUES(SEQ_PIECE_NO.NEXTVAL, 2, 'https://firebasestorage.googleapis.com/v0/b/odagirijoe-3e3a4.firebasestorage.app/o/piece%2F%EC%83%98%ED%94%8C%20(17).jpg?alt=media&token=8812128d-d5e2-42fc-87cc-38612e349e07',
			 '대쉬보드 테스트1', '판매완료', 13, 13, DEFAULT, 1, 'F', 6);
INSERT INTO PIECE
VALUES(SEQ_PIECE_NO.NEXTVAL, 2, 'https://firebasestorage.googleapis.com/v0/b/odagirijoe-3e3a4.firebasestorage.app/o/piece%2F%EC%83%98%ED%94%8C%20(17).jpg?alt=media&token=8812128d-d5e2-42fc-87cc-38612e349e07',
			 '대쉬보드 테스트2', '판매완료', 13, 13, DEFAULT, 1, 'F', 1);
INSERT INTO PIECE
VALUES(SEQ_PIECE_NO.NEXTVAL, 2, 'https://firebasestorage.googleapis.com/v0/b/odagirijoe-3e3a4.firebasestorage.app/o/piece%2F%EC%83%98%ED%94%8C%20(17).jpg?alt=media&token=8812128d-d5e2-42fc-87cc-38612e349e07',
			 '대쉬보드 테스트2', '판매완료', 13, 13, DEFAULT, 1, 'F', 3);
INSERT INTO PIECE
VALUES(SEQ_PIECE_NO.NEXTVAL, 2, 'https://firebasestorage.googleapis.com/v0/b/odagirijoe-3e3a4.firebasestorage.app/o/piece%2F%EC%83%98%ED%94%8C%20(17).jpg?alt=media&token=8812128d-d5e2-42fc-87cc-38612e349e07',
			 '대쉬보드 테스트2', '판매완료', 13, 13, '2024-11-28', 1, 'F', 3);
INSERT INTO PIECE
VALUES(SEQ_PIECE_NO.NEXTVAL, 2, 'https://firebasestorage.googleapis.com/v0/b/odagirijoe-3e3a4.firebasestorage.app/o/piece%2F%EC%83%98%ED%94%8C%20(17).jpg?alt=media&token=8812128d-d5e2-42fc-87cc-38612e349e07',
			 '대쉬보드 테스트2', '판매완료', 13, 13, '2024-11-30', 1, 'F', 3);
INSERT INTO PIECE
VALUES(SEQ_PIECE_NO.NEXTVAL, 2, 'https://firebasestorage.googleapis.com/v0/b/odagirijoe-3e3a4.firebasestorage.app/o/piece%2F%EC%83%98%ED%94%8C%20(17).jpg?alt=media&token=8812128d-d5e2-42fc-87cc-38612e349e07',
			 '대쉬보드 테스트2', '판매완료', 13, 13, '2024-11-30', 1, 'F', 3);
INSERT INTO PIECE
VALUES(SEQ_PIECE_NO.NEXTVAL, 2, 'https://firebasestorage.googleapis.com/v0/b/odagirijoe-3e3a4.firebasestorage.app/o/piece%2F%EC%83%98%ED%94%8C%20(17).jpg?alt=media&token=8812128d-d5e2-42fc-87cc-38612e349e07',
			 '대쉬보드 테스트22', '판매완료', 13, 13, '2024-11-30', 1, 'F', 3);
INSERT INTO PIECE
VALUES(SEQ_PIECE_NO.NEXTVAL, 2, 'https://firebasestorage.googleapis.com/v0/b/odagirijoe-3e3a4.firebasestorage.app/o/piece%2F%EC%83%98%ED%94%8C%20(17).jpg?alt=media&token=8812128d-d5e2-42fc-87cc-38612e349e07',
			 '대쉬보드 테스트22', '판매완료', 13, 13, '2024-12-02', 1, 'F', 3);
			
			
			
			

			
INSERT INTO PAYMENT_RECORD
VALUES(1, SEQ_MEMBER_NO.NEXTVAL , SEQ_PIECE_NO.NEXTVAL, 'payment-1ea96184-e64e-45d8-823e-542f476d', 2000000, DEFAULT, '대쉬보드', 01012345678 );

SELECT COUNT(*)
		FROM
			PIECE
		WHERE MEMBER_NO = 2
		AND   PIECE_STATUS IN ('N', 'F', 'A', 'S');
	
SELECT
			A.MEMBER_NO, A.ARTIST_PROFILE, A.ARTIST_NICKNAME,
			 LISTAGG(W.WORK_DETAIL, ', ') WITHIN GROUP (ORDER BY W.WORK_DETAIL) AS WORK_DETAILS,
			
			(SELECT COUNT(*) FROM FOLLOW WHERE MEMBER_NO = A.MEMBER_NO) AS FOLLOW_COUNT,
			
			(SELECT COUNT(*)
				FROM FOLLOW
				WHERE MEMBER_NO = 1
				AND   ARTIST_NO = 39) AS FOLLOW_CHECK 
			
		FROM 
			ARTIST A
		LEFT JOIN 
			MEMBER M ON (A.MEMBER_NO = M.MEMBER_NO)
		LEFT JOIN 
			WORK W ON (A.MEMBER_NO = W.MEMBER_NO)
		WHERE
			A.MEMBER_NO = 39
		AND 
			M.MEMBER_DEL_FL = 'N'
		GROUP BY 
   		   A.MEMBER_NO, A.ARTIST_PROFILE, A.ARTIST_NICKNAME;
			
			
			
			
			
			
INSERT INTO "WORK"
VALUES(SEQ_WORK_NO.NEXTVAL, 8, '2024 on the hill, a fresh breeze, 세종갤러리 기획전');
INSERT INTO "WORK"
VALUES(SEQ_WORK_NO.NEXTVAL, 8, '2021년 현대미술 공모전 입선');
			
			
			
INSERT INTO PIECE_SELL
VALUES(46, 1000000);
INSERT INTO PIECE_SELL
VALUES(14, 1000000);
			
			



